# Generated by Django 4.2 on 2023-05-10 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_limit',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0, 'Daily limit must be positive')]),
        ),
    ]
